//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrConsole.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.IUser")]
    public interface IUser {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetUserInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo", ReplyAction="http://tempuri.org/IUser/GetUserInfoResponse")]
        XrConsole.TestService.GetUserInfoResponse GetUserInfo(XrConsole.TestService.GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo", ReplyAction="http://tempuri.org/IUser/GetUserInfoResponse")]
        System.Threading.Tasks.Task<XrConsole.TestService.GetUserInfoResponse> GetUserInfoAsync(XrConsole.TestService.GetUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 methodName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CommandUser", ReplyAction="http://tempuri.org/IUser/CommandUserResponse")]
        XrConsole.TestService.CommandUserResponse CommandUser(XrConsole.TestService.CommandUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CommandUser", ReplyAction="http://tempuri.org/IUser/CommandUserResponse")]
        System.Threading.Tasks.Task<XrConsole.TestService.CommandUserResponse> CommandUserAsync(XrConsole.TestService.CommandUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public XrConsole.TestService.GetUserInfoRequestBody Body;
        
        public GetUserInfoRequest() {
        }
        
        public GetUserInfoRequest(XrConsole.TestService.GetUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserInfoRequestBody {
        
        public GetUserInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public XrConsole.TestService.GetUserInfoResponseBody Body;
        
        public GetUserInfoResponse() {
        }
        
        public GetUserInfoResponse(XrConsole.TestService.GetUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInfoResult;
        
        public GetUserInfoResponseBody() {
        }
        
        public GetUserInfoResponseBody(string GetUserInfoResult) {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandUser", Namespace="http://tempuri.org/", Order=0)]
        public XrConsole.TestService.CommandUserRequestBody Body;
        
        public CommandUserRequest() {
        }
        
        public CommandUserRequest(XrConsole.TestService.CommandUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string methodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlPara;
        
        public CommandUserRequestBody() {
        }
        
        public CommandUserRequestBody(string methodName, string xmlPara) {
            this.methodName = methodName;
            this.xmlPara = xmlPara;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CommandUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public XrConsole.TestService.CommandUserResponseBody Body;
        
        public CommandUserResponse() {
        }
        
        public CommandUserResponse(XrConsole.TestService.CommandUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CommandUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CommandUserResult;
        
        public CommandUserResponseBody() {
        }
        
        public CommandUserResponseBody(string CommandUserResult) {
            this.CommandUserResult = CommandUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : XrConsole.TestService.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<XrConsole.TestService.IUser>, XrConsole.TestService.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XrConsole.TestService.GetUserInfoResponse XrConsole.TestService.IUser.GetUserInfo(XrConsole.TestService.GetUserInfoRequest request) {
            return base.Channel.GetUserInfo(request);
        }
        
        public string GetUserInfo() {
            XrConsole.TestService.GetUserInfoRequest inValue = new XrConsole.TestService.GetUserInfoRequest();
            inValue.Body = new XrConsole.TestService.GetUserInfoRequestBody();
            XrConsole.TestService.GetUserInfoResponse retVal = ((XrConsole.TestService.IUser)(this)).GetUserInfo(inValue);
            return retVal.Body.GetUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrConsole.TestService.GetUserInfoResponse> XrConsole.TestService.IUser.GetUserInfoAsync(XrConsole.TestService.GetUserInfoRequest request) {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrConsole.TestService.GetUserInfoResponse> GetUserInfoAsync() {
            XrConsole.TestService.GetUserInfoRequest inValue = new XrConsole.TestService.GetUserInfoRequest();
            inValue.Body = new XrConsole.TestService.GetUserInfoRequestBody();
            return ((XrConsole.TestService.IUser)(this)).GetUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XrConsole.TestService.CommandUserResponse XrConsole.TestService.IUser.CommandUser(XrConsole.TestService.CommandUserRequest request) {
            return base.Channel.CommandUser(request);
        }
        
        public string CommandUser(string methodName, string xmlPara) {
            XrConsole.TestService.CommandUserRequest inValue = new XrConsole.TestService.CommandUserRequest();
            inValue.Body = new XrConsole.TestService.CommandUserRequestBody();
            inValue.Body.methodName = methodName;
            inValue.Body.xmlPara = xmlPara;
            XrConsole.TestService.CommandUserResponse retVal = ((XrConsole.TestService.IUser)(this)).CommandUser(inValue);
            return retVal.Body.CommandUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XrConsole.TestService.CommandUserResponse> XrConsole.TestService.IUser.CommandUserAsync(XrConsole.TestService.CommandUserRequest request) {
            return base.Channel.CommandUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<XrConsole.TestService.CommandUserResponse> CommandUserAsync(string methodName, string xmlPara) {
            XrConsole.TestService.CommandUserRequest inValue = new XrConsole.TestService.CommandUserRequest();
            inValue.Body = new XrConsole.TestService.CommandUserRequestBody();
            inValue.Body.methodName = methodName;
            inValue.Body.xmlPara = xmlPara;
            return ((XrConsole.TestService.IUser)(this)).CommandUserAsync(inValue);
        }
    }
}
